### ISSUE TITLE
Python3

### ISSUE THREAD

**Issue by jcricaurte** [mkesicki/excel_validator#14]
Dear, 
I was testing your script but it seems to fail with python 3. 
Dict variables are not supported. 
I'm getting errors on type = settings.keys()[0]

**Comment by mkesicki** [comment]
It was done for 2.X version. Feel free to update it. As you figured out already I am not checking here to often...

**Comment by mkesicki** [comment]
It was moved to python 3 in https://github.com/mkesicki/excel_validator/pull/16 by @JohnElmasry
