### ISSUE TITLE
Addressing error file size limitation

### ISSUE THREAD

**Issue by tiagofilipesilva** [mkesicki/excel_validator#18]
https://github.com/mkesicki/excel_validator/blob/f1ef7593f7c085fac666d349a06d5571dbd19418/excel_validator.py#L282

Hi,

I think this is a great tool, but there seems to be a limitation regarding the binary size of the error Excel file.

If I try to run against an input file that is between 76 -- 100 megabits Excel file, I receive an error saying that the output error file is too large and thus cannot be created.

As a user (with sufficient resource) my expectation is for a file to be generated.
Does anyone more versed in the code of the solution and/or supporting libraries provide me with enlightenment on how to bypass this situation?

Thank you.

**Comment by mkesicki** [comment]
As fair as I remember (I created this code very long time ago), this limitation was added to avoid situation of using too much resources for parsing huge files. The excel file of the size you mention is huge :) and creating "annotated" copy of it might be a "killer". The first idea I have is that we can add config parameter to skip this check or prompt user if he/she is sure what is doing (even better, I think).
As quick fix you can comment the line from your comment in code and check what will happen :)

**Comment by mkesicki** [comment]
@tiagofilipesilva:

Requested change added in:
 https://github.com/mkesicki/excel_validator/pull/19
